// ── Field types ───────────────────────────────────────────────
// text | textarea | number | date | datetime | select | boolean | file | url | sdg_multi | proof_upload | profile_picture_upload

const SDG = [
  // sdg_goals stores comma-separated SDG numbers e.g. "3,7,13"
  // sdg_details is a free-text explanation
  { key: 'sdg_goals',   label: 'SDG Goals (select all that apply)',       type: 'sdg_multi' },
  { key: 'sdg_details', label: 'Brief details of how it relates to SDG',  type: 'textarea',
    conditionalOn: { key: 'sdg_goals', value: '__nonempty__' } },
]

// Report name format hint shown to faculty
const REPORT_NAME_HINT = 'Format: {Sr.No}_{Tab Name}_{Your Name} e.g. 5_Publications_DrRaviKant'

// Tabs with proof required (proof is meaningful for these)
export const PROOF_REQUIRED_TABS = [
  'tab2','tab4','tab5','tab6','tab7','tab8','tab9',
  'tab10','tab11','tab12','tab13','tab14','tab15','tab16','tab19','tab20'
]

const PROOF = [
  {
    key:      'drive_link',
    label:    'Upload PDF Proof',
    type:     'proof_upload',
    required: false,   // enforced dynamically in TabForm based on PROOF_REQUIRED_TABS
  },
]


// SDG list — also used by SDGSelector component and DataViewer export
export const SDG_LIST = [
  { num: 1,  label: 'No Poverty' },
  { num: 2,  label: 'Zero Hunger' },
  { num: 3,  label: 'Good Health and Well-being' },
  { num: 4,  label: 'Quality Education' },
  { num: 5,  label: 'Gender Equality' },
  { num: 6,  label: 'Clean Water and Sanitation' },
  { num: 7,  label: 'Affordable and Clean Energy' },
  { num: 8,  label: 'Decent Work and Economic Growth' },
  { num: 9,  label: 'Industry, Innovation and Infrastructure' },
  { num: 10, label: 'Reduced Inequalities' },
  { num: 11, label: 'Sustainable Cities and Communities' },
  { num: 12, label: 'Responsible Consumption and Production' },
  { num: 13, label: 'Climate Action' },
  { num: 14, label: 'Life Below Water' },
  { num: 15, label: 'Life on Land' },
  { num: 16, label: 'Peace, Justice and Strong Institutions' },
  { num: 17, label: 'Partnerships for the Goals' },
]

export const ACADEMIC_YEARS = ['2024-25','2023-24','2022-23','2021-22','2020-21','2019-20']

export const TABS = [
  {
    id: 'tab1', number: 1, name: 'Faculty Information',
    table: 'tab1_faculty_info', icon: '👤', isProfile: true,
    description: 'Personal academic and professional profile. One record per faculty.',
    fields: [
      { key: 'profile_picture',              label: 'Profile Picture',                         type: 'profile_picture_upload' },
      { key: 'contact_number',               label: 'Contact Number',                          type: 'text',    required: true },
      { key: 'employee_code',                label: 'Employee Code (Salary Slip)',              type: 'text',    required: true },
      { key: 'appar_id',                     label: 'APPAR ID (if any)',                        type: 'text' },
      { key: 'vidwan_id',                    label: 'Vidwan ID',                                type: 'text' },
      { key: 'orcid',                        label: 'ORCID (16 digits)',                        type: 'text' },
      { key: 'scopus_id',                    label: 'SCOPUS ID (11 digits)',                    type: 'text' },
      { key: 'researcher_id',               label: 'Researcher ID / WoS (9 digits)',            type: 'text' },
      { key: 'google_scholar_id',           label: 'Google Scholar Profile ID (from URL)',       type: 'text' },
      { key: 'citations_count',             label: 'Total Citations (from Scholar/Scopus)',       type: 'number' },
      { key: 'h_index',                     label: 'h-index',                                     type: 'number' },
      { key: 'i10_index',                   label: 'i10-index',                                   type: 'number' },
      { key: 'area_of_specialization',      label: 'Area of Specialization',                    type: 'textarea', required: true },
      { key: 'is_phd_guide',               label: 'Recognised as PhD Research Guide?',          type: 'select', options: ['Yes', 'No'], required: true },
      { key: 'year_phd_guide_recognition',  label: 'Year of Recognition as Research Guide',     type: 'text',   conditionalOn: { key: 'is_phd_guide', value: 'Yes' } },
      { key: 'highest_degree',             label: 'Highest Degree',                             type: 'select', options: ['PhD', 'Post-Doc', 'D.Sc.', 'Other'], required: true },
      { key: 'highest_degree_month_year',  label: 'Month & Year of Passing Highest Degree',     type: 'text',   required: true },
      { key: 'highest_degree_specialization', label: 'Specialization of Highest Degree',        type: 'text',   required: true },
      { key: 'highest_degree_university',  label: 'University/Institute of Highest Degree',     type: 'text',   required: true },
      { key: 'mtech_specialization',       label: 'M.Tech / M.E. Specialization',               type: 'text' },
      { key: 'mtech_month_year',           label: 'Month & Year of Passing M.Tech / M.E.',      type: 'text' },
      { key: 'mtech_degree',              label: 'M.Tech / M.E. Degree Name',                   type: 'text' },
      { key: 'mtech_university',           label: 'University/Institute of M.Tech / M.E.',       type: 'text' },
      { key: 'date_of_joining',           label: 'Date of Joining PDEU',                         type: 'date',   required: true },
      { key: 'designation_at_joining',    label: 'Designation at Time of Joining',               type: 'text',   required: true },
      { key: 'present_designation',       label: 'Present Designation',                          type: 'select', options: ['Assistant Professor', 'Associate Professor', 'Professor', 'Other'], required: true },
      { key: 'date_promotion_asst_prof',  label: 'Date of Promotion – Assistant Professor',      type: 'date' },
      { key: 'date_promotion_assoc_prof', label: 'Date of Promotion – Associate Professor',      type: 'date' },
      { key: 'date_promotion_prof',       label: 'Date of Promotion – Professor',                type: 'date' },
      { key: 'total_experience',          label: 'Total Experience (years)',                      type: 'number', required: true },
      { key: 'teaching_experience',       label: 'Teaching Experience (years)',                   type: 'number', required: true },
      { key: 'teaching_experience_pdeu',  label: 'Teaching Experience at PDEU (years)',           type: 'number', required: true },
      { key: 'industry_experience',       label: 'Industry Experience (years)',                    type: 'number' },
      { key: 'other_experience',          label: 'Any Other Experience (years)',                   type: 'number' },
      { key: 'nature_of_associate',       label: 'Nature of Associate at PDEU',                   type: 'select', options: ['Regular', 'Contract', 'Adjunct', 'Visiting', 'Other'] },
    ],
  },

  {
    id: 'tab2', number: 2, name: 'Faculty & Student Achievements',
    table: 'tab2_achievements', icon: '🏆',
    description: 'Awards and achievements — by faculty or students guided by faculty.',
    fields: [
      { key: 'details',            label: 'Details about Achievement',                            type: 'textarea', required: true },
      { key: 'achievement_level',  label: 'Achievement Level',                                    type: 'select', options: ['International', 'National', 'State', 'University'], required: true },
      { key: 'achievement_type',   label: 'Type',                                                 type: 'select', options: ['Faculty Achievement', 'Student Achievement', 'Student Achievement – Faculty as Guide'], required: true },
      { key: 'achievement_date',   label: 'Achievement Date',                                     type: 'date',   required: true },
      { key: 'academic_year',      label: 'Academic Year',                                        type: 'select', options: ACADEMIC_YEARS, required: true },
      { key: 'awarding_agency',    label: 'Name of Awarding Agency',                              type: 'text',   required: true },
      { key: 'outcome',            label: 'Outcome (fund received or other details)',              type: 'textarea' },
      { key: 'student_roll_names', label: 'Roll Number & Name of Students (if applicable)',       type: 'textarea' },
      ...SDG, ...PROOF,
    ],
  },

  {
    id: 'tab3', number: 3, name: 'Faculty Subject Mapping',
    table: 'tab3_subject_mapping', icon: '📚',
    description: 'Courses taught — Even and Odd semesters.',
    fields: [
      { key: 'academic_year',         label: 'Academic Year',                         type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'semester_type',         label: 'Semester',                              type: 'select', options: ['Even', 'Odd'], required: true },
      { key: 'course_name',           label: 'Name of Course',                        type: 'text',   required: true },
      { key: 'semester',              label: 'Semester Number',                        type: 'text',   required: true },
      { key: 'division',              label: 'Division',                               type: 'text' },
      { key: 'theory_or_lab',         label: 'Theory / Lab',                           type: 'select', options: ['Theory', 'Lab', 'Theory & Lab'] },
      { key: 'batch',                 label: 'Batch',                                  type: 'text' },
      { key: 'course_code',           label: 'Course Code',                            type: 'text',   required: true },
      { key: 'branch_and_semester',   label: 'Branch & Semester',                      type: 'text' },
      { key: 'cc_name',               label: 'Course Coordinator Name',                type: 'text' },
      { key: 'course_file_submitted', label: 'Course File Submitted?',                 type: 'select', options: ['Yes', 'No'] },
      { key: 'mid_qp_uploaded',       label: 'Mid Question Paper Uploaded?',           type: 'select', options: ['Yes', 'No'] },
      { key: 'mid_qp_link',           label: 'Mid Question Paper Link',                type: 'url' },
      { key: 'end_qp_uploaded',       label: 'End Question Paper Uploaded?',           type: 'select', options: ['Yes', 'No'] },
      { key: 'end_qp_link',           label: 'End Question Paper Link',                type: 'url' },
    ],
  },

  {
    id: 'tab4', number: 4, name: 'PhD Student Details',
    table: 'tab4_phd_students', icon: '🎓',
    description: 'Details of PhD students supervised.',
    fields: [
      { key: 'supervisor_1',    label: 'Name of Supervisor I',                         type: 'text', required: true },
      { key: 'supervisor_2',    label: 'Name of Supervisor II (if any)',                type: 'text' },
      { key: 'student_name',    label: 'Student Name',                                 type: 'text', required: true },
      { key: 'roll_no',         label: 'Roll No.',                                     type: 'text', required: true },
      { key: 'enrollment_year', label: 'Academic Year of Enrollment',                  type: 'text', required: true },
      { key: 'enrollment_type', label: 'Type of Enrollment',                           type: 'select', options: ['Full-time', 'Part-time'], required: true },
      { key: 'start_date',      label: 'Start Date',                                   type: 'date', required: true },
      { key: 'degree_status',   label: 'Degree Status',                                type: 'select', options: ['Ongoing', 'Awarded'], required: true },
      { key: 'end_date',        label: 'End Date (if Degree Awarded)',                  type: 'date', conditionalOn: { key: 'degree_status', value: 'Awarded' } },
      { key: 'thesis_title',    label: 'Thesis Title',                                 type: 'textarea' },
      ...SDG, ...PROOF,
    ],
  },

  {
    id: 'tab5', number: 5, name: 'Publications & Conferences',
    table: 'tab5_publications', icon: '📄',
    description: 'Journal papers, conference presentations, and book chapters.',
    fields: [
      { key: 'pub_type',               label: 'Type',                                  type: 'select', options: ['Journal Paper', 'Conference Paper', 'Book Chapter', 'Book', 'Other'], required: true },
      { key: 'status',                 label: 'Status',                                type: 'select', options: ['Published', 'Accepted', 'Under Review', 'Presented'], required: true },
      { key: 'title',                  label: 'Title of Publication',                  type: 'textarea', required: true },
      { key: 'peer_reviewed',          label: 'Peer Reviewed?',                        type: 'select', options: ['Yes', 'No'] },
      { key: 'subscription_type',      label: 'Subscription Type',                     type: 'select', options: ['Open Access', 'Subscription'] },
      { key: 'author_number',          label: 'Your Author Number',                    type: 'text' },
      { key: 'coauthors',              label: 'All Co-authors (separated by ";")',      type: 'textarea' },
      { key: 'coauthor_affiliations',  label: 'Co-author Affiliations (by ";")',        type: 'textarea' },
      { key: 'collaboration_institutes', label: 'Collaboration Institutes / Industry', type: 'textarea' },
      { key: 'btech_coauthor',         label: 'B.Tech Student as Co-author?',          type: 'select', options: ['Yes', 'No'] },
      { key: 'btech_roll_numbers',     label: 'B.Tech Roll Numbers',                   type: 'text', conditionalOn: { key: 'btech_coauthor', value: 'Yes' } },
      { key: 'mtech_coauthor',         label: 'M.Tech Student as Co-author?',          type: 'select', options: ['Yes', 'No'] },
      { key: 'mtech_roll_numbers',     label: 'M.Tech Roll Numbers',                   type: 'text', conditionalOn: { key: 'mtech_coauthor', value: 'Yes' } },
      { key: 'phd_coauthor',           label: 'PhD Student as Co-author?',             type: 'select', options: ['Yes', 'No'] },
      { key: 'phd_roll_numbers',       label: 'PhD Roll Numbers',                      type: 'text', conditionalOn: { key: 'phd_coauthor', value: 'Yes' } },
      { key: 'journal_or_conf_name',   label: 'Journal / Conference / Book Name',      type: 'text', required: true },
      { key: 'impact_factor',          label: 'Impact Factor of Journal',              type: 'number' },
      { key: 'volume_no',              label: 'Volume No.',                             type: 'text' },
      { key: 'issue_no',               label: 'Issue No.',                              type: 'text' },
      { key: 'page_nos',               label: 'Page Numbers',                           type: 'text' },
      { key: 'publisher_name',         label: 'Publisher Name',                         type: 'text' },
      { key: 'doi',                    label: 'DOI',                                    type: 'text' },
      { key: 'academic_year',          label: 'Academic Year',                          type: 'select', options: ACADEMIC_YEARS, required: true },
      { key: 'pub_date',               label: 'Date of Publication / Conference',       type: 'date' },
      { key: 'event_place',            label: 'Event Institute & Place (conference)',   type: 'text' },
      { key: 'website_link',           label: 'Website Link',                           type: 'url' },
      ...SDG, ...PROOF,
    ],
  },

  {
    id: 'tab6', number: 6, name: 'Projects & Consultancy',
    table: 'tab6_projects', icon: '🔬',
    description: 'Research projects, consultancy, and other funded activities.',
    fields: [
      { key: 'title',               label: 'Title of Project / Consultancy',           type: 'textarea', required: true },
      { key: 'status',              label: 'Status',                                   type: 'select', options: ['Ongoing', 'Completed'], required: true },
      { key: 'project_type',        label: 'Type',                                     type: 'select', options: ['Research Project', 'Consultancy', 'Other'], required: true },
      { key: 'start_date',          label: 'Start Date',                               type: 'date' },
      { key: 'end_date',            label: 'End Date',                                 type: 'date' },
      { key: 'academic_year',       label: 'Academic Year',                            type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'funding_agency',      label: 'Name of Funding Agency',                   type: 'text' },
      { key: 'pi_name',             label: 'Name of PI',                               type: 'text',   required: true },
      { key: 'copi_name',           label: 'Co-PI Name & Affiliation',                 type: 'textarea' },
      { key: 'student_involvement', label: 'Student Involvement in Work',              type: 'textarea' },
      { key: 'journal_papers',      label: 'No. of Journal Papers Published',          type: 'number' },
      { key: 'conference_papers',   label: 'No. of Conference Papers Presented',       type: 'number' },
      { key: 'patents_published',   label: 'No. of Patents Published',                 type: 'number' },
      { key: 'facilities_developed', label: 'Facilities Developed under Project',      type: 'textarea' },
      { key: 'working_models',      label: 'No. of Working Models / Prototypes',       type: 'number' },
      { key: 'btech_graduated',     label: 'No. of B.Tech Students Graduated',         type: 'number' },
      { key: 'phd_graduated',       label: 'No. of PhD Students Graduated',            type: 'number' },
      { key: 'me_graduated',        label: 'No. of M.E. Students Graduated',           type: 'number' },
      { key: 'amount_generated',    label: 'Amount Generated (₹)',                     type: 'number' },
      { key: 'funding_year1',       label: 'Funding Received – Year 1 (₹)',            type: 'number' },
      { key: 'funding_year2',       label: 'Funding Received – Year 2 (₹)',            type: 'number' },
      { key: 'funding_year3',       label: 'Funding Received – Year 3 (₹)',            type: 'number' },
      { key: 'funding_year4',       label: 'Funding Received – Year 4 (₹)',            type: 'number' },
      { key: 'funding_year5',       label: 'Funding Received – Year 5 (₹)',            type: 'number' },
      ...SDG, ...PROOF,
    ],
  },

  {
    id: 'tab7', number: 7, name: 'Patents & Prototypes',
    table: 'tab7_patents', icon: '💡',
    description: 'Patents filed / granted and working prototypes developed.',
    fields: [
      { key: 'inventor_name',         label: 'Name of Inventor',                      type: 'text',   required: true },
      { key: 'inventor_order',        label: 'Order in Inventors List',                type: 'text' },
      { key: 'other_inventors',       label: 'Other Inventors (in sequence)',           type: 'textarea' },
      { key: 'other_inventors_affil', label: 'Affiliations of Other Inventors',        type: 'textarea' },
      { key: 'students_involved',     label: 'Name of Students Involved (if any)',     type: 'textarea' },
      { key: 'activity_type',         label: 'Activity Type',                          type: 'select', options: ['Patent – Filed', 'Patent – Published', 'Patent – Granted', 'Prototype / Working Model', 'Copyright', 'Other'], required: true },
      { key: 'academic_year',         label: 'Academic Year',                          type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'grant_date',            label: 'Date of Grant / Publication / Production', type: 'date' },
      { key: 'awarded_by',            label: 'Awarded By (Patent Office)',              type: 'text' },
      { key: 'patent_number',         label: 'Patent / Model Number',                  type: 'text' },
      { key: 'brief_detail',          label: 'Brief Detail of Patent / Model',          type: 'textarea' },
      { key: 'website_link',          label: 'Website Link (if applicable)',             type: 'url' },
      ...SDG, ...PROOF,
    ],
  },

  {
    id: 'tab8', number: 8, name: 'Meetings, Alumni & Parent Interactions',
    table: 'tab8_meetings', icon: '🤝',
    description: 'Department meetings, alumni interactions, parent–teacher meets.',
    fields: [
      { key: 'meeting_details', label: 'Details of Meeting / Interaction',             type: 'textarea', required: true },
      { key: 'activity_type',   label: 'Activity Type',                                type: 'select', options: ['Department Meeting', 'Alumni Interaction', 'Parent–Teacher Meet', 'Other'], required: true },
      { key: 'start_datetime',  label: 'Start Date & Time',                            type: 'datetime', required: true },
      { key: 'end_time',        label: 'End Time',                                     type: 'text' },
      { key: 'academic_year',   label: 'Academic Year',                                type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'venue',           label: 'Venue',                                        type: 'text',   required: true },
      { key: 'organizer',       label: 'Organizer / Coordinator',                      type: 'text' },
      { key: 'alumni_details',  label: 'Details of Alumni / Visiting Person',          type: 'textarea' },
      ...PROOF,
    ],
  },

  {
    id: 'tab9', number: 9, name: 'Talks, Workshops, STTP & FDP',
    table: 'tab9_talks_workshops', icon: '🎤',
    description: 'Expert talks, workshops, STTPs, FDPs organised by the faculty.',
    fields: [
      { key: 'event_name',          label: 'Name / Topic of Event',                   type: 'text',   required: true },
      { key: 'event_type',          label: 'Type of Event',                            type: 'select', options: ['Expert Talk', 'Workshop', 'STTP', 'FDP', 'Webinar', 'Seminar', 'Other'], required: true },
      { key: 'category',            label: 'Category',                                 type: 'text' },
      { key: 'skill_enhancement',   label: 'Related to Skill Enhancement?',            type: 'select', options: ['Yes', 'No'] },
      { key: 'expert_name',         label: 'Name of Expert',                           type: 'text' },
      { key: 'expert_affiliation',  label: 'Affiliation of Expert',                    type: 'text' },
      { key: 'start_date',          label: 'Start Date',                               type: 'date',   required: true },
      { key: 'end_date',            label: 'End Date',                                 type: 'date',   required: true },
      { key: 'academic_year',       label: 'Academic Year',                            type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'no_of_days',          label: 'No. of Days',                              type: 'number' },
      { key: 'venue',               label: 'Venue',                                    type: 'text' },
      { key: 'organizer',           label: 'Organizer / Coordinator',                  type: 'text' },
      { key: 'target_audience',     label: 'Target Audience',                          type: 'text' },
      { key: 'btech_attendees',     label: 'No. of B.Tech Attendees',                  type: 'number' },
      { key: 'mtech_attendees',     label: 'No. of M.Tech Attendees',                  type: 'number' },
      { key: 'outside_professionals', label: 'No. of Outside Professionals',           type: 'number' },
      { key: 'level',               label: 'Level',                                    type: 'select', options: ['National', 'International', 'Internal'] },
      { key: 'fund_received',       label: 'Fund Received / Collected (₹)',            type: 'number' },
      { key: 'fund_details',        label: 'Fund Details (Agency / Registration Fees)', type: 'textarea' },
      { key: 'fund_utilized',       label: 'Fund Utilized (₹)',                         type: 'number' },
      ...SDG, ...PROOF,
    ],
  },

  {
    id: 'tab10', number: 10, name: 'Professional Memberships',
    table: 'tab10_memberships', icon: '🏅',
    description: 'Memberships in national / international professional societies.',
    fields: [
      { key: 'grade_level',      label: 'Grade / Level / Position',                   type: 'text',   required: true },
      { key: 'society_name',     label: 'Name of Professional Society / Body',         type: 'text',   required: true },
      { key: 'membership_id',    label: 'Membership ID',                               type: 'text' },
      { key: 'national_or_intl', label: 'National or International?',                  type: 'select', options: ['National', 'International'], required: true },
      ...PROOF,
    ],
  },

  {
    id: 'tab11', number: 11, name: 'Faculty Certifications / MOOCs',
    table: 'tab11_certifications', icon: '🎖️',
    description: 'SWAYAM, NPTEL and other approved MOOC certifications obtained.',
    fields: [
      { key: 'course_name',    label: 'Name of Course Passed',                         type: 'text',   required: true },
      { key: 'academic_year',  label: 'Academic Year',                                  type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'offered_by',     label: 'Course Offered By',                              type: 'text',   required: true },
      { key: 'grade_obtained', label: 'Grade Obtained',                                 type: 'text',   required: true },
      ...SDG, ...PROOF,
    ],
  },

  {
    id: 'tab12', number: 12, name: 'e-Content Developed',
    table: 'tab12_econtent', icon: '🎬',
    description: 'Courses developed for SWAYAM / NPTEL / e-PG Pathshala and other platforms.',
    fields: [
      { key: 'course_name',   label: 'Name of Course Developed',                       type: 'text',   required: true },
      { key: 'academic_year', label: 'Academic Year',                                   type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'coauthors',     label: 'Name of Co-authors (if any)',                     type: 'text' },
      { key: 'platform_name', label: 'Platform (SWAYAM / NPTEL / e-PG / Other)',        type: 'text',   required: true },
      { key: 'online_link',   label: 'Online Link of the Course',                       type: 'url' },
      ...PROOF,
    ],
  },

  {
    id: 'tab13', number: 13, name: 'Faculty Support in Student Projects',
    table: 'tab13_student_projects', icon: '🚀',
    description: 'Mentoring / facilitating student innovation – hackathons, ideathons, etc.',
    fields: [
      { key: 'event_name',          label: 'Name of Event',                            type: 'text',   required: true },
      { key: 'activity_type',       label: 'Activity Type',                             type: 'select', options: ['Hackathon', 'Ideathon', 'Open Research', 'Innovation Contest', 'Internship Mentoring', 'Other'], required: true },
      { key: 'activity_type_other', label: 'Specify if Other',                          type: 'text',   conditionalOn: { key: 'activity_type', value: 'Other' } },
      { key: 'academic_year',       label: 'Academic Year',                             type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'start_date',          label: 'Start Date',                                type: 'date' },
      { key: 'end_date',            label: 'End Date',                                  type: 'date' },
      { key: 'place',               label: 'Place of Event',                            type: 'text' },
      { key: 'organizer',           label: 'Organizer / Coordinator',                   type: 'text' },
      { key: 'website_link',        label: 'Website Link (if any)',                     type: 'url' },
      ...SDG, ...PROOF,
    ],
  },

  {
    id: 'tab14', number: 14, name: 'Faculty Training & Collaboration',
    table: 'tab14_training', icon: '🏭',
    description: 'Industry internships, training programs, and research collaborations.',
    fields: [
      { key: 'training_name',    label: 'Name of Internship / Training / Collaboration', type: 'text',   required: true },
      { key: 'activity_type',    label: 'Activity Type',                                  type: 'select', options: ['Industry Internship', 'Research Collaboration', 'Training Program', 'FDP', 'Other'], required: true },
      { key: 'academic_year',    label: 'Academic Year',                                  type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'start_date',       label: 'Start Date',                                     type: 'date' },
      { key: 'end_date',         label: 'End Date',                                       type: 'date' },
      { key: 'duration_days',    label: 'Duration (No. of Days)',                         type: 'number' },
      { key: 'place',            label: 'Place of Event',                                 type: 'text' },
      { key: 'outcomes',         label: 'Outcomes of Training / Collaboration',            type: 'textarea', required: true },
      { key: 'outcome_details',  label: 'Details of Outcomes',                            type: 'textarea' },
      { key: 'publication_link', label: 'Link of Publication (if applicable)',             type: 'url' },
      ...SDG, ...PROOF,
    ],
  },

  {
    id: 'tab15', number: 15, name: 'Faculty as Resource Persons',
    table: 'tab15_resource_persons', icon: '🎙️',
    description: 'Faculty invited as resource persons for STTP / FDP / Expert Talks elsewhere.',
    fields: [
      { key: 'event_name',    label: 'Name of STTP / FDP / Expert Talk',               type: 'text',   required: true },
      { key: 'academic_year', label: 'Academic Year',                                   type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'start_date',    label: 'Start Date',                                      type: 'date',   required: true },
      { key: 'end_date',      label: 'End Date',                                        type: 'date' },
      { key: 'location',      label: 'Location',                                        type: 'text',   required: true },
      { key: 'organised_by',  label: 'Organised By',                                   type: 'text',   required: true },
      ...PROOF,
    ],
  },

  {
    id: 'tab16', number: 16, name: 'Industrial Visits',
    table: 'tab16_industrial_visits', icon: '🏗️',
    description: 'Industrial visits organized for students.',
    fields: [
      { key: 'faculty_coordinator',    label: 'Faculty Coordinator of Visit',          type: 'text',   required: true },
      { key: 'academic_year',          label: 'Academic Year',                          type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'industry_name',          label: 'Name of Industry / Organization',        type: 'text',   required: true },
      { key: 'industry_address',       label: 'Address (City, State)',                  type: 'text',   required: true },
      { key: 'visit_date',             label: 'Date of Visit',                          type: 'date',   required: true },
      { key: 'duration',               label: 'Duration (e.g. Half day / 2 days)',       type: 'text',   required: true },
      { key: 'student_semester',       label: 'Semester of Students',                   type: 'text' },
      { key: 'faculty_accompanied',    label: 'Faculty Accompanied',                    type: 'text' },
      { key: 'industry_contact_email', label: 'Email of Industry Contact Person',       type: 'text' },
      { key: 'students_participated',  label: 'No. of Students Participated',           type: 'number', required: true },
      { key: 'purpose',                label: 'Purpose of Visit',                        type: 'select', options: ['Academic Learning', 'Internship Scouting', 'Project Work', 'Industry Exposure', 'Other'] },
      { key: 'industry_feedback',      label: 'Feedback from Industry (if any)',         type: 'textarea' },
      { key: 'proof_available',        label: 'Proof of Visit Available?',               type: 'select', options: ['Yes', 'No'] },
      { key: 'drive_link',             label: 'OneDrive / Drive Link',                   type: 'file' },
      { key: 'report_name',            label: 'Name of Report',                          type: 'text' },
    ],
  },

  {
    id: 'tab17', number: 17, name: 'Academic Courses in Innovation',
    table: 'tab17_innovation_courses', icon: '💼',
    description: 'Courses related to Innovation, Entrepreneurship, and IPR.',
    fields: [
      { key: 'academic_year',  label: 'Academic Year',                                  type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'course_title',   label: 'Title of Course',                                type: 'text',   required: true },
      { key: 'course_code',    label: 'Course Code',                                    type: 'text',   required: true },
      { key: 'course_type',    label: 'Type of Course',                                 type: 'select', options: ['Core Course', 'Elective Course'], required: true },
      { key: 'course_level',   label: 'Level',                                          type: 'select', options: ['UG', 'PG', 'PhD'],               required: true },
      { key: 'department',     label: 'Offering Department / Centre / Unit',             type: 'text',   required: true },
      { key: 'total_credits',  label: 'Total Credit Score',                             type: 'number', required: true },
    ],
  },

  {
    id: 'tab18', number: 18, name: 'Placement Data',
    table: 'tab18_placement', icon: '🏢',
    description: 'B.Tech student placement details.',
    fields: [
      { key: 'roll_no',        label: 'Roll No.',                                       type: 'text',   required: true },
      { key: 'student_name',   label: 'Student Name',                                   type: 'text',   required: true },
      { key: 'academic_year',  label: 'Academic Year (Batch)',                           type: 'select', options: ACADEMIC_YEARS,   required: true },
      { key: 'branch',         label: 'Branch',                                          type: 'text',   required: true },
      { key: 'cpi',            label: 'CPI',                                             type: 'number' },
      { key: 'placement_type', label: 'Placement Type',                                  type: 'select', options: ['Placed via Campus', 'Placed Independently', 'Own Business', 'Higher Studies', 'Other'], required: true },
      { key: 'company_name',   label: 'Company Name',                                    type: 'text' },
      { key: 'ctc',            label: 'CTC (LPA)',                                        type: 'number' },
      { key: 'proof_link',     label: 'Proof / Company Email Link',                      type: 'file' },
    ],
  },

  {
    id: 'tab19', number: 19, name: 'MOU Details',
    table: 'tab19_mou', icon: '📝',
    description: 'Memoranda of Understanding with institutions and industries.',
    fields: [
      { key: 'organisation_name',    label: 'Organisation with which MoU is Signed',   type: 'text',   required: true },
      { key: 'institution_industry', label: 'Name of Institution / Industry',           type: 'text',   required: true },
      { key: 'mou_date',             label: 'Date of Signing MoU',                      type: 'date',   required: true },
      { key: 'mou_duration',         label: 'Duration of MoU',                          type: 'text',   required: true },
      { key: 'activities_list',      label: 'Activities under MoU (year-wise)',          type: 'textarea' },
      { key: 'activity_name',        label: 'Name of Activity / Event',                 type: 'text' },
      { key: 'activity_type',        label: 'Type of Activity / Event',                 type: 'text' },
      { key: 'faculty_organizer',    label: 'Name of Faculty Organizer',                type: 'text' },
      { key: 'activity_dates',       label: 'Activity Dates',                            type: 'text' },
      { key: 'attendees_count',      label: 'Approx. No. of Attendees',                 type: 'number' },
      { key: 'event_report_link',    label: 'Event Report Link',                        type: 'file' },
    ],
  },

  {
    id: 'tab20', number: 20, name: 'Internal Research Grants',
    table: 'tab20_research_grants', icon: '💰',
    description: 'Institution seed money / internal research grants received.',
    fields: [
      { key: 'project_title',        label: 'Project Title / Support for Activity',    type: 'text',     required: true },
      { key: 'academic_year',        label: 'Academic Year',                            type: 'select', options: ACADEMIC_YEARS,     required: true },
      { key: 'duration',             label: 'Duration',                                 type: 'text' },
      { key: 'amount_lacs',          label: 'Amount (Lacs ₹)',                          type: 'number',   required: true },
      { key: 'amount_utilized_lacs', label: 'Amount Utilized (Lacs ₹)',                type: 'number' },
      { key: 'outcomes',             label: 'Outcomes of the Project',                  type: 'textarea' },
      ...SDG,
    ],
  },
]

export const ADMIN_TAB_MAP = {
  tab1: 'Salman',  tab2: 'Krunal',       tab3: 'Vivek Jaiswal', tab4: 'Salman',
  tab5: 'Anirudh', tab6: 'Anirudh',      tab7: 'Anirudh',       tab8: 'Abhinaya',
  tab9: 'Abhinaya', tab10: 'Abhinaya',   tab11: 'Vivek Jaiswal', tab12: 'Vivek Jaiswal',
  tab13: 'Krunal', tab14: 'Abhinaya',    tab15: 'Abhinaya',     tab16: 'Salman',
  tab17: 'Vivek Jaiswal', tab18: 'Krunal', tab19: 'Anirudh',   tab20: 'Anirudh',
}

export const ADMINS        = ['Salman', 'Krunal', 'Vivek Jaiswal', 'Anirudh', 'Abhinaya']
export const getTab         = id => TABS.find(t => t.id === id)
